@tidl 1.0.0;
interface Algebra exposes MathService {
	@description "
Title
=====

Overview of the Algebra Api

Features
--------
* Addition
* Substraction
";

	int add(int x,int y){
		@description "add x & y";
	}

	int substract(int x,int y){
		@description "substract x & y";

	}
}