@tidl 2.0.0;
service MathService{
	interface Sample exposes  {
		@description "
			Title
			=====

			Overview of the Algebra Api

			Features
			--------
			* json
			* Sum
			* Difference
		";
	@version 1.0.0;

		int getSum(int x, int y){
			@description "calculate x + y";
		}

		int getDifference(int x, int y){
			@description "calculate x-y";
		}
	}
}